Dev branch
mikhaylov123ty/go-first-floor-sprint-five pull request #1
Opened 2023-12-28 08:55 UTC by mikhaylov123ty

2023-12-28 12:36 UTC, robotomize requested changes
Хорошая работа, но есть несколько ошибок, котоыре нужно исправить

2023-12-28 12:36 UTC, robotomize commented on main.go
> +	return float64(t.Action) * LenStep / MInKm
Тут затаилась ошибка=)  У вас LenStep это константа

2023-12-28 12:36 UTC, robotomize commented on main.go
> +	if w.Weight == 0 {
Отлично, проверили краевой случай

2023-12-28 12:36 UTC, robotomize commented on main.go
> +	meanSpeedInMsec := w.meanSpeed() * KmHInMsec
Хорошая разбивка на предпосчитанные результаты

2023-12-28 12:36 UTC, robotomize commented on main.go
> +	return float64(s.LengthPool*s.CountPool/MInKm) / s.Duration.Hours()
Тут в первой части выражения интересный нюанс. Мы получим целое число в результате деления, а нам нужно дробное. Попробуйте подставить различные значения и вывести среднюю скорость, она будет скорее всего равна 0

2023-12-28 20:25 UTC, mikhaylov123ty commented
@robotomize спасибо за фидбек! поправил замечания и недочеты.

2023-12-30 01:17 UTC, robotomize approved these changes
Отлично, хорошая работа! Принято! С наступающим!

2025-03-31 10:17 UTC, merged